config/routes.rb
Blog::Application.routes.draw do

get 'tags/:tag', to: 'posts#index', as: :tag

root to: "posts#index"


resources :posts do
  resources :comments
end

get '/about', to: 'pages#about'
get '/change_language', to: "posts#change_language"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActiveModel::Serializers::JSON

  belongs_to :post
  attr_accessible :body, :tel, :rates, :show_comment, :full_name
  attr_accessor :full_name

  validates :tel, presence: true, length: { minimum: 9 }

  scope :saved_comments,  where('id NOT ?', nil)


  # setter
  def full_name=(val)
    self.name = val.split(' ')[0]
    self.last_name = val.split(' ')[1]
  end

  # getter
  def full_name
    current_full_name = ""
     if name.present?
       current_full_name = "#{name} #{last_name}"
     end
     current_full_name
  end

  def show_comment?
    current_show_comment = ""
    if show_comment == TRUE
      current_show_comment = "Yes"
    else
      current_show_comment = "No"
    end
    current_show_comment
  end


end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::Serializers::JSON
  ORDER_OPTION = ['id', 'title', 'amount']

  serialize :tags, Array

  has_many :comments, dependent: :destroy
  attr_accessible :body, :title, :amount, :avr_rates, :tags, :photo, :email

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  validate :calculate_number_of_words


  has_attached_file :photo, :styles => { :small => "150x150>", :medium => "300x300>", :large => "520x520>"},
                     :url  => "/assets/posts/:id/:style/:basename.:extension",
                     :path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']


  def calculate_number_of_words
    total_value = 30
    non_html = ActionView::Base.full_sanitizer.sanitize(body.to_s)
    if non_html.to_s.split(' ').size > total_value
      errors.add(:discount, "can't be more then 30 words")
    end
  end

  def average_rate
      arr_rate= comments.collect(&:rates).compact
      self.avr_rates = (arr_rate.sum / arr_rate.size.to_f).round(2)
  end


  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  def as_json(options={})
    super(:only => [:title,:body,:email,:avr_rates],
          :include => {
            :comments => {:only => [:body, :name, :last_name]}
          }
    )
  end

  # setter
  def tags=(val)
    if val.present?
      tags_arr = val.split(', ').compact
      write_attribute(:tags, tags_arr)
    end
  end

  #getter
  def tags
    read_attribute(:tags)
  end


  def self.number_of_tags
    h = ""
    array_of_tags = Post.all.collect{|t| t.tags}.flatten
    h = array_of_tags.each_with_object(Hash.new(0)) { |word,counts| counts[word] += 1 }
    h
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment].permit(:body, :tel, :rates, :full_name))

    if @comment.save
      PostMailer.new_comment(@post).deliver

      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      render 'posts/show'
    end


  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update_attributes(params[:comment].permit(:body, :tel,:show_comment, :rates))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
PER_PAGE = 5

  def index
      @posts = Post.order(params["options_order"]).page(params[:page]).per_page(PER_PAGE).search(params[:search])

      respond_to do |format|
        format.html
        format.json {
          render :json => @posts.to_json( :include => [:comments] )
        }
        format.xml {
          render :xml => @posts.to_xml( :include => [:comments] )
        }
      end
  end

  def new
    @post = Post.new

  end

  def show
    @post = Post.find(params[:id])
    @post.average_rate

    respond_to do |format|
      format.html
    	format.json {
        render :json => @post.to_json( :include => [:comments] )
      }
      format.xml {
        render :xml => @post.to_xml( :include => [:comments] )
      }
    end

  end


  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post].permit(:title, :tags, :body, :amount, :avr_rates, :photo, :email))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def change_language
    I18n.locale = 'he' || I18n.default_locale

    redirect_to :back
  end

private

  def post_params
    params.require(:post).permit(:title, :tags, :body, :amount, :avr_rates, :photo, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
  <div class="commit clearfix">
    <div class="comment_content">
      <p class="comment_name"><span>Commet full name:</span> <strong><%=comment.full_name %></strong></p>
      <p class="comment_body"><span>Commet body: </span><%= comment.body %></p>
      <p class="comment_time"><span>Commet created at: </span><%= time_ago_in_words(comment.created_at) %> ago </p>

        <% if comment.rates.present? %>
         <p class="comment_rate"><span>Commet rates: </span>
           <% (0..comment.rates-1).to_a.each do |rate| %>
              <i class="fa fa-star" aria-hidden="true"></i>
           <% end %>
         </p>
        <% end %>

      <p> <span>Commet if  show: </span><%= comment.show_comment? %></p>
    </div>

    <p class="delete">
      <%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' } %>
    </p>
    <p class="edit">
      <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %>
    </p>
  </div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @comment.present? ? @comment : @post.comments.build]) do |f| %>
  <p>
    <%= f.label :full_name %> </br>
    <%= f.text_field :full_name %>
  </p>

  <p>
    <%= f.label :tel %> </br>
    <%= f.text_field :tel %>
  </p>

  <p>
    <%= f.label :body %> </br>
    <%= f.text_area :body %>
  </p>

  <p>
      rates:  <%= f.select :rates, (0..5) %>
  </p>

  <p>
      Show comment: <%= f.check_box :show_comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/comments/create.js.erb
$("div#comments h2").html("<%= pluralize(@post.comments.count, 'comments') %>");
$("div#comments").append("<%= escape_javascript(render(:partial => @comment)) %>");
$("#new_comment")[0].reset();
$("#comments").html("<%= escape_javascript(render @post.comments) %>");

app/views/comments/edit.html.erb
<h1>edit comment</h1>
 <%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "javascripts/jquery-3.2.1.min" %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="screen, projection">

  <%= csrf_meta_tags %>
</head>
<body>
<div id="sidebar">
  <div id="logo">
    <%= link_to root_path do %>
       <%= image_tag "logo.png" %>
       <% end %>
  </div>

  <div id="tags_counter">
    <h3><b>The number of tags:</b></h3>
    <ul id="tag_count">
      <% Post.number_of_tags.each do |key, value| %>
        <li> <%= "#{key} is #{value}"  %></li>
      <% end %>
    </il>
  </div>

  <ul>
    <li class="category">Website</li>
    <li><%= link_to "Blog", root_path %></li>
    <li><%= link_to "about", about_path %></li>
  </ul>

  <ul>
    <li class="category">Social</li>
    <li><a href="gfgdf">Twiter</a></li>
    <li><a href="gfgdf">Twiter</a></li>
    <li><a href="gfgdf">Twiter</a></li>
    <li><a href="gfgdf">Twiter</a></li>
  </ul>

</div>

<div id="main_content">
  <div id="header">
    <div class="buttons">
      <p class="button"><%= link_to "all posts" , posts_path %> </p>
      <div class="button"><%= link_to "new post" , new_post_path %></div>
      <div class="button"><%= link_to "change language" , change_language_path %></div>
    </div>
  </div>
</div>

<% flash.each do |name,msg| %>
  <% content_tag(:div, msg, class:"alert") %>

<% end %>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
    <h1>Hey.</h1>
    <p>
      what is Lorem Ipsum?
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

      Why do we use it?
      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

    </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= tinymce_assets %>

<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
  <div id="error">
    <h2><%= pluralize(@post.errors.count, "error") %> preventes this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, class: "tinymce" %>
  </p>

  <p>
     <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= tinymce %>

app/views/posts/_pos.html.erb
<% @posts.each do |post|  %>
   <div class="post_wrapper">
        <h2 class="title">
          Title: <%= link_to post.title , post %>
        </h2>
        <p>Tags: <%= post.tags %></p>
        <p class="date">
          Created at: <%= post.created_at.strftime("%B, %d, %Y") %>
        </p>
        <p class="amount">
          Number of amount: <%= post.amount %>
        </p>
        <p class="email">
            Email: <%= post.email %>
        </p>
   </div>
<% end %>

app/views/posts/_post.html.erb
<% @posts.each do |post|  %>
   <div class="post_wrapper">
        <h2 class="title">
          Title: <%= link_to post.title , post %>
        </h2>
        <p>Tags: <%= post.tags %></p>
        <p class="date">
          Created at: <%= post.created_at.strftime("%B, %d, %Y") %>
        </p>
        <p class="amount">
          Number of amount: <%= post.amount %>
        </p>
   </div>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>edit post</h1>
 <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<%= form_tag posts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<%= form_tag posts_path, :method => 'get' do %>
  <p>
    <%= select_tag "options_order", options_for_select(Post::ORDER_OPTION) %>
    <%= submit_tag "Update" %>
  </p>
<% end %>


<div id="posts">
  <%= will_paginate @posts, previous_label: h("<"), next_label: h(">") %>
  <%= render 'post' %>
</div>

app/views/posts/new.html.erb
<h1>new post</h1>

<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
<div id="error">
  <h2><%= pluralize(@post.errors.count, "error") %>preventes this post from saving</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>


<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <b><%= t 'post_content.title' %> </b><%= @post.title %>
  </h1>
  <% if @post.photo.present? %>
    <div>
      <%= image_tag @post.photo.url(:large) %>
    </div>
  <% end %>

  <% if @post.avr_rates.present? %>
    <p class="avrRate">
      <b><%= t 'post_content.rate' %> </b><%= @post.avr_rates %>
    </p>
  <% end %>

  <% if @post.email.present? %>
    <p class="email">
      <b><%= t 'post_content.email' %> </b><%= @post.email  %>
    </p>
  <% end %>

  <% if @post.tags.present? %>
    <p class="tags">
      <b><%= t 'post_content.tags' %> </b><%= raw @post.tags.collect { |t| link_to t, tag_path(t) }.join(', ')  %>
    </p>
  <% end %>

  <p class="body">
    <b><%= t 'post_content.body' %>  </b><%= raw @post.body %>
  </p>

  <p class="date">
    submitted <%= time_ago_in_words(@post.created_at)  %> ago
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'are you sure?'} %>

  </p>


  <div id="comments">
    <% if @comment.present? && @comment.errors.any? %>
    <div id="error">
      <h2><%= pluralize(@comment.errors.count, "error") %> preventes this comments from saving</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <h2><%= @post.comments.count %> comments</h2>
    <%= render @post.comments.saved_comments %>

    <div id="new_comments">
      <h3><%= t 'post_content.comment' %> </h3>
      <%= render "comments/form" %>
    </div>

  </div>
</div>